/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebooksharing_susan;

/**
 *
 * @author indrajit
 */

import java.awt.Toolkit;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;


public class RegistrationPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPanel
     */
    public RegistrationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        SignInButton = new javax.swing.JButton();
        UserPassTextField = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(400, 400));

        UserNameLabel.setText("UserName");

        PasswordLabel.setText("PassWord");

        SignInButton.setText("Sign In");
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLabel)
                            .addComponent(PasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SignInButton)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(UserPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(SignInButton)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        // TODO add your handling code here:

        String UserNameText = "";
        String delim = ",";
        String PassWordText = "";
        UserNameText = this.UserNameTextField.getText();
        PassWordText = this.UserPassTextField.getText();

        try {
            DbConnector dbc = new DbConnector();

            Connection conn = dbc.Connects();
            //Class.forName("org.apache.derby.jdbc.ClientDriver");
            //conn = DriverManager.getConnection("jdbc:derby://localhost:1527/UsersRegistration", "java", "java");
            Statement User_Stmt = conn.createStatement();
            String User_query = "Select * from UserInfo";
            ResultSet User_result = User_Stmt.executeQuery(User_query);
            boolean checkmatch = false;
            boolean SuperUserType = false;
            boolean UserType = false;

            String usernametogui = "";
            if (!UserNameText.isEmpty() && !PassWordText.isEmpty()) {
                while (User_result.next()) {
                    String UN = User_result.getString("UserName");
                    String PW = User_result.getString("Password");

                    if (UN.equalsIgnoreCase(UserNameText) && PW.equals(PassWordText)) {
                        checkmatch = true;
                        usernametogui = User_result.getString("firstName");
                        SuperUserType = User_result.getBoolean("is_SU");
                    }

                }

                if (checkmatch) {
                    if(SuperUserType){
                        //JOptionPane.showMessageDialog(null, "You are logged in as  Super user.");
                        cancel();
                        SuperUser su = new SuperUser(usernametogui);
                        su.setVisible(true);
                    }
                    else if(!SuperUserType){
                        //JOptionPane.showMessageDialog(null, "You are logged in as registered user.");
                        cancel();
                        RegUserPage rup = new RegUserPage("Register User", usernametogui);
                        rup.setVisible(true);
                    }
                    else{
                        cancel();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid creditials, Try again.");
                    this.UserNameTextField.setText("");
                    this.UserPassTextField.setText("");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "All fields are required");

            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_SignInButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JPasswordField UserPassTextField;
    // End of variables declaration//GEN-END:variables

public void cancel(){
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

}
